### ISSUE TITLE
Numbers don't have commas instead of periods based on locale

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#130]
**Summary:** 

In the app, the following fields don't change periods to commas in numbers based on locale:
- [x] PDOP
- [x] C/N0
- [x] Elev
- [x] Azim
- [x] Carrier frequency

For example:

![image](https://user-images.githubusercontent.com/928045/37744418-69952778-2d45-11e8-9c9a-0c9e35bc55f9.png)

**Steps to reproduce:** 

1. Change to a locale where commas are used in place of periods in numbers (e.g., Swedish - `sv_SE`)
1. Run the app and view the Status screen

**Expected behavior:** 

Show me commas in numbers in place of periods

**Observed behavior:** 

In the following fields periods are still shown:
* PDOP
* C/N0
* Elev
* Azim

**Device and Android version:** 

Visible on a Galaxy S9+ screenshot w/ Android 8.0 shared by user

**Comment by goldfndr** [comment]
Would it make sense to simply drop the ",0" or ".0" at the end if all the values end the same way? In every screenshot I've seen, they all were integers, which makes me think that adding tenths make it appear to be more accurate than it actually is.

**Comment by barbeau** [comment]
@goldfndr That's a good question - I've observed the same.  However, they are floating point values coming from the Android APIs, so I'd prefer the leave open the possibility that some devices may provide further precision.

**Comment by goldfndr** [comment]
Do you think it's possible that some future device might have tenths (or higher) accuracy but have some readings in which all C/N0 and Elev and Azimuth values are integers?

**Comment by barbeau** [comment]
Good question - I'm not sure.  Since these values come from native code they will differ by OEM and chipset, so I'd expect to see a variety of formats and values.

**Comment by goldfndr** [comment]
Er, just Elev and Azim – I've observed tenths on SNR.

**Comment by goldfndr** [comment]
If one has just 3 satellites with elevation and azimuth, there's a one in a million chance of them having zero tenths when they'd ordinarily have non-zero tenths. Divide probability by 100 for each additional satellite.

So, it'd be quite safe to check that they all are integers (==Math.rint or zero for modulo 1 or whatever) and not display tenths if so.

>they are floating point values

A nearly identical argument could be made that they should be displayed with 6 decimal digits instead of 1, as that's the approximate resolution in the 0-360 range.

Come to think of it, there's probably a way to determine what location accuracy would be needed to require tenths of elevation/azimuth degrees. 3 meters wouldn't trigger it, but perhaps 0.5 meters (or less) would.
