### ISSUE TITLE
SBAS for Australasia

### ISSUE THREAD

**Issue by kimollivier** [barbeau/gpstest#271]
![2019-04-01 12 59 03](https://user-images.githubusercontent.com/3343876/55297916-02743880-5487-11e9-8305-57e10e9aea5e.jpg)
**Summary:** 

Australia and New Zealand now have SBAS on PRN 122

**Steps to reproduce:** 

This does not show as available

**Expected behavior:** 

List 122 in NZ as available
https://www.ga.gov.au/scientific-topics/positioning-navigation/positioning-for-the-future/satellite-based-augmentation-system
The trial has been extended while a permanent signal is formalised.

**Observed behavior:** 

SBAS not available

**Device and Android version:** 

Samsung Note 8

**Screenshots:** 
![image](https://user-images.githubusercontent.com/3343876/55297940-364f5e00-5487-11e9-9367-6e39b2ba99ea.png)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by barbeau** [comment]
Thanks! Can you add a screenshot of this on the Note 8?

**Comment by barbeau** [comment]
@kimollivier From a closer look at your screenshot, it looks like your device hardware doesn't support the Australia SBAS, otherwise it would show the record in the SBAS card but the flag would be missing.  I've been holding off adding support for specific satellites like this to GPSTest until there is evidence of hardware support.  So, I'll keep this issue open until we can find a device that actually supports it.

**Comment by barbeau** [comment]
News on this front:
https://www.minister.industry.gov.au/ministers/pitt/media-releases/australia-nz-boost-satellite-positioning-technology

Looks like the new SBAS will be called the "Southern Positioning Augmentation Network", or SPAN.

**Comment by LukePrior** [comment]
Hi, I think this should be reopened as open services on southpan have recently been enabled.

https://communication.ga.gov.au/link/id/zzzz633276f5c3808450Pzzzz5eeb356d5558b601/page.html

https://communication.ga.gov.au/link/id/zzzz633276f5c4b2a114Pzzzz5eeb356d5558b601/page.html
