### ISSUE TITLE
Improve documentation formatting and display

### ISSUE THREAD

**Issue by Meteor0id** [barbeau/gpstest#323]
Currently the explanation for the app is hidden under Menu > Help > About which is not where most users would go when they are looking to a usemanual

It is named a FAQ but that is not what it is. It is more of a legend or manual to using the app.

Proposing bring the Changelog menu en the About menu to the main menu. Than add a 3rd menu named "useguide" or something like that and move the explanations to there.

The main menu would have the following items
- Settings
- Userguide
- Send feedback
- Changelog
- Acknowledgements

**Comment by barbeau** [comment]
So here's the brief history of GPSTest documentation:

I originally started with just a FAQ in the GitHub repo.  Users were pretty clear that they preferred in-app text, so I implemented the "Help->About" screen. "About" got translated to many languages by contributors within the app, which is awesome.  However, it's an ongoing pain for everyone because it's poorly formatted and huge. In the currently format you simply can't represent tables or figures, so over time these have gotten thrown into FAQ as they've been developed.

So, I'm definitely in favor of improving the overall documentation of GPSTest.

I do, however, want to keep the current navigation drawer simple, so "Help" will continue to be the main entry point to all documentation.  I'm open to alternate designs from there, though, including re-formatting in-app help text into HTML, etc.  In a perfect world we'd have something that renders well in a web browser for richer content that can also be translated.

I'd certainly welcome help in this effort.  Given the limited time I have to work on the app I'm not likely to overhaul this in the near-term.
