### ISSUE TITLE
GNSS CF (Japan)

### ISSUE THREAD

**Issue by KovalevArtem** [barbeau/gpstest#493]
**Describe the bug**
The displayed data, which I highlighted with a red rectangle, is it a bug?

**App, Device and Android version:** 
Xiaomi Mi 10 lite 5G (M2002J9G)
Android 11
GPSTest 3.9.10

**Screenshots:** 
![image](https://user-images.githubusercontent.com/36500228/112494165-d77e0000-8d93-11eb-857e-888c06424745.png)

**Comment by barbeau** [comment]
@KovalevArtem Thanks for the report! Yes, this looks like a bug in Xiaomi's implementation - there is no QZSS frequency of 1561.098 MHz. You can see real-world GNSS carrier frequencies here - https://github.com/barbeau/gpstest/blob/master/FAQ.md#does-gpstest-support-dual-frequency-gnss.

I'm going to close this issue because it's not a GPSTest issue, but I'd strongly suggest reporting this to Xiaomi (it's not the first Xiaomi bug like this) and reporting back here what they say.
