### ISSUE TITLE
More Clearly Named Logs

### ISSUE THREAD

**Issue by vkbellis** [barbeau/gpstest#507]
Within its own sub folder created for each instance of GPSTest run, clearly name the log files; e.g.,
gnss_log_nmea_2021_04_19_13_42_52.nmea
gnss_log_nav_messages_2021_04_19_13_42_52.21N (.yyN)
gnss_log_rinex_2021_04_19_13_42_52.21o 
gnss_log_location_fixes_2021_04_19_13_42_52.txt
gnss_log_antenna_info_2021_04_19_13_42_52.csv
gnss_log_antenna_info_2021_04_19_13_42_52.json

**Comment by barbeau** [comment]
In order to keep compatibility with GnssLogger and tools (see https://developer.android.com/guide/topics/sensors/gnss) as mentioned in another issue, I'm going to keep the same format with all records in the same CSV file. It complicates code significantly to have options to write to the same file or multiple files. The records can be split out fairly easily in existing tools that process CSV files by grouping on the first column that identifies the type of record and then stripping off the first column.
