### ISSUE TITLE
[question] LineageOS 18.1 / h850 : no data = broken hardware ?

### ISSUE THREAD

**Issue by msharp1** [barbeau/gpstest#539]
Hi,
I'm a bit out of topic here, sorry about that, but I thought I could get a quick answer from here. I own a h850 with LineageOS 18.1 installed. I have no idea if the GPS was working before the stock ROM got wiped. I installed GPSTest and there is zero data displayed in the home screen of the app. Does it means the localization hardware is broken or maybe it's not expected to work out of the box with LOS ?

**Comment by barbeau** [comment]
I think the Google Group is a better venue for this question as you might find others with the same or similar setup there:
https://groups.google.com/g/gpstest_android

I have a stock LG G5 that's very slow to show any satellites, so I don't know if there is an issue with server-side support for assistance data that's part of the problem. With custom ROMs there is always a chance of something breaking related to GPS, especially if the custom ROM Android version doesn't equal the original stock ROM Android version because that driver interface changes over time.

I'm going to close this issue as it's not an issue with GPSTest per se, but please feel free to provide any updates if you find more info.
