### ISSUE TITLE
Library/SDK for other apps

### ISSUE THREAD

**Issue by ryust** [barbeau/gpstest#561]
Have you considered an open source library/SDK that could be embedded in other apps to improve location accuracy? Google talks about the GNSS API to get sub-meter accuracy, but there doesn't seem to be any implementations anywhere that Android apps could utilize. Odd Google doesn't add something to their fused location provider.

**Comment by barbeau** [comment]
@ryust That would certainly be nice, although GPSTest itself doesn't current compute it's own location based on raw measurements so there isn't anything here that could be put into a library right now. 

That being said, it's a type of library I'd like to see and I have encouraged Google to offer such a thing. The closest that Google currently has is the [GnssLogger](https://github.com/google/gps-measurement-tools#gnsslogger) app, but Google recently stopped open-source development on that and is working off an internal fork now.

There are a few other candidate open-source Android apps for this that I've listed here:
https://github.com/barbeau/awesome-gnss#android-apps-open-source

I'm going to close this issue because it's not a GPSTest Android app feature per se, but please feel free to comment with any additional information or to coordinate creating such a library.

>Odd Google doesn't add something to their fused location provider.

If you read https://www.gpsworld.com/google-to-improve-urban-gps-accuracy-for-apps/ it sounds like Google's magic is indeed available to apps via the fused location provider, but that's obvious a black box.
