### ISSUE TITLE
License in Github not set up correctly ?

### ISSUE THREAD

**Issue by aha999** [barbeau/gpstest#573]
**Describe the bug**
Badge from Shields.io doesn't recognize your github project license, meaning you probably didn't set it up properly.

**Expected behavior**
Shields.io badges should recognize your license.

you should see the badge set up in my fork: https://github.com/aha999/gpstest/blob/master/README.md

**Comment by barbeau** [comment]
@aha999 Thanks for flagging this, it should be fixed in https://github.com/barbeau/gpstest/commit/6ba53f194812896164bb72c99e5f8f3e6ba27e4f. The original file predated GitHub's templates for licenses, so now I'm using their official Apache v2.0 template. Seems to reflect correctly in the badge and on the repo homepage.
