### ISSUE TITLE
GNSS lock with only 2 satellites

### ISSUE THREAD

**Issue by altayhunter** [barbeau/gpstest#685]
**Describe the bug**
GNSS is said to require a [mininum of 3 satellites](https://gis.stackexchange.com/questions/12866) to obtain a lock, but I've seen GPSTest obtain a lock occasionally with as few as 2 satellites even from a cold start. Is this somehow expected under unusual circumstances, or is GPSTest mistaken about something?

**To Reproduce**
1. Go somewhere with weak GNSS signal (e.g. indoors).
2. Run GPSTest for a while.
3. Under the right conditions it will obtain a lock with just 2 satellites (then typically lose it again immediately).

**Expected behavior**
A minimum of 3 satellites are required for a lock, or maybe no fewer than 4.

**Observed behavior**
Sometimes a lock is obtained with just 2 satellites.

**App, Device and Android version:** 
Device: OnePlus 7 Pro
GPSTest: v3.10.3 (24097-google)
Android: 14 - 20240607
ROM: YAAP-14-Urshanabi-guacamole-20240607
Google Play services: version 24.22.13 (190400-638740827)

**Screenshots:**
![Screenshot_20240614-112337_GPSTest](https://github.com/barbeau/gpstest/assets/871691/4dcd562c-9290-4094-8529-3f7a2acc854a)

**Comment by barbeau** [comment]
Thanks for the repot! GPSTest shows the values reported by the GNSS chipset, so looks like there is indeed an error in the values the device is reporting.

Could you please open an issue for this at https://buganizer.corp.google.com/issues/new?component=313183&template=1021001 and include the same info (and link to the issue here)?

I'm going to close this as "Won't fix" here because there isn't anything I can do in GPSTest to fix it.
