### ISSUE TITLE
App can't be downloaded from Google Play on Android 13 and 14

### ISSUE THREAD

**Issue by Torinde** [barbeau/gpstest#694]
Can't install it on Android 14 - Play store says "not supported by device".

**Comment by JonnyTech** [comment]
Which device??

**Comment by barbeau** [comment]
GPSTest supports all Android versions 7.0 and up. What model device are you using? 

You can always try the FDroid version too - https://f-droid.org/packages/com.android.gpstest.osmdroid/

**Comment by JonnyTech** [comment]
> Pixel 5

Stock ROM?

**Comment by barbeau** [comment]
I would suggest making sure that the Play Store is fully updated, and if that doesn't work try reaching out to Pixel Help:
https://support.google.com/pixelphone/gethelp?sjid=4364861620608164982-AP

AFAIK there isn't anything I can do to help with this, but please post an update if you're able to find a fix!

**Comment by JonnyTech** [comment]
I would also suggest that if Play Store is somehow misbehaving then try **Aurora Store** (an alternative client for Play Store) from [GitLab](https://gitlab.com/AuroraOSS/AuroraStore/-/releases) or [FDroid](https://f-droid.org/en/packages/com.aurora.store/).

**Comment by JonnyTech** [comment]
@barbeau is it related to this?: https://stackoverflow.com/questions/75515890/this-app-isnt-available-for-your-device-because-it-was-made-for-an-older-versio

@Torinde did you try the FDroid build or to install using Aurora? It would be good to know if they work.

**Comment by barbeau** [comment]
So to summarize known workarounds that can be used on Android 13/14 devices until I fix this issue:
1. Download the Google build flavor APK from GitHub - https://github.com/barbeau/gpstest/releases/download/v3.10.3/googleRelease-v3.10.3.apk
1. Install GPSTest from the F-Droid store - https://f-droid.org/packages/com.android.gpstest.osmdroid/. Note that this won't have GoogleMaps but will use OSM tiles instead, which can be flaky because they're free.
1. Use GnssLogger instead, which has similar features - https://play.google.com/store/apps/details?id=com.google.android.apps.location.gps.gnsslogger

**Comment by barbeau** [comment]
Google Play won't let me submit an update with targetSdkVersion 33 - it needs to be 34. From https://developer.android.com/google/play/requirements/target-sdk:

>New apps and *app updates* must target Android 14 (API level 34) or higher to be submitted to Google Play

**Comment by barbeau** [comment]
As soon as Google approves v3.10.5 and it rolls out to all users, the app should be available on Android 13 and up again through Google Play.

More at:
https://groups.google.com/g/gpstest_android/c/uWIhpiCoTuI

**Comment by barbeau** [comment]
v3.10.5 should now be available to everyone via Google Play.

Please give it a try and let me know if you see any problems!
