### ISSUE TITLE
No GLONASS or BEIDOU fix 

### ISSUE THREAD

**Issue by djdookie** [barbeau/gpstest#80]
**Summary:** 

I don't get any GLONASS or BEIDOU fixes with my Galaxy S5 Android 7.1.1 (LineageOS 14.1), GPS only. But I can see all satellites.

**Steps to reproduce:** 

Install LineageOS 14.1 (Android 7.1.1) on Samsung S5 (klte) and activate GPS.
Then install GPS Test and watch GPS getting fixed, but no fix from GLONASS or BEIDOU.

**Expected behavior:** 

Get a fix from all visible satellites from all three hardware supported navigation systems.

**Observed behavior:** 

Can also be reproduced with other GPS test tools. So I don't really know where the problem is coming from. But I don't know if it's Android 7 (Nougat) problems, because the API changed to level 24 and the old GPS function got deprecated. Or if it's a driver problem. Or if it is an implementation problem with LineageOS. I also reported that problem in their forums: https://www.reddit.com/r/LineageOS/comments/62zfdr/no_glonass_fix_with_galaxy_s5/

**Device and Android version:** 

Samsung Galaxy S5 (klte) with
https://mirrorbits.lineageos.org/full/klte/20170329/lineage-14.1-20170329-nightly-klte-signed.zip
and
https://github.com/opengapps/arm/releases/download/20170401/open_gapps-arm-7.1-micro-20170401.zip

**Screenshots:** 

![Screenshot1](https://i.imgur.com/haOKwjt.png)
![Screenshot2](https://i.imgur.com/D0ypH6J.png)

**Comment by barbeau** [comment]
@djdookie This would be an issue with LineageOS.  The screenshot above is for the wrong app, though - could you add a screenshot from this app (download on Google Play at https://play.google.com/store/apps/details?id=com.android.gpstest).

**Comment by djdookie** [comment]
@barbeau Hi, oh sorry I was in a hurry and posted the wrong screen. I fixed that!
I tried multiple tools to see if it's a problem of this app. Your's was the only one who was able to switch between the native and the new GNSS Android 7.0 interface.
Because I didn't get any replies on LineageOS reddit yet and you seemed to have knowledge about the API, I thought I'd try to ask here if this could be an Android problem, not just LineageOS?

**Comment by barbeau** [comment]
Thanks!  Very unlikely to be Android AOSP issue - I have an Android 7.0 device (LG G5) that's able to see GLONASS sats.  Thinking more, it's likely a native code issue where the "usedInFix" bit isn't being set before the GNSS updates are being passed to the Android framework, which is where apps grab the data from.  The APIs in Android changed significantly for Android 7.0 to properly support multiple GNSS constellations, so there is likely a breakdown between the old S5 native code and the new Android 7.0 platform/API.  Note that GLONASS and Beidou *could* potentially still be used by your GNSS chipset when computing a location fix (assuming they were supported in hardware to begin with), it may just be that the mechanism for reporting to apps whether or not each sat was used in a fix is broken.  So, this may not technically be a LineageOS issue either - it could just be a mismatch between the native stock drivers for GNSS hardware and Android 7.0, because the native drivers weren't designed for the new Android 7.0 GNSS engine/API structure.

Also, I assume you saw GLONASS and Beidou sats being used for fixes on your S5 with the stock OS, which is why you're asking the question now?

Also, I'm going to close out this issue as it's definitely not a problem with GPSTest.

**Comment by djdookie** [comment]
Yeah, there is no problem with the stock rom, and i believe Android 6 had no problems.
Thanks for your answers. I had the same idea, that it could just be the reporting to apps mechanism and not the hardware. But how can I find out?
I posted the issue here now: https://jira.lineageos.org/browse/REGRESSION-295

**Comment by barbeau** [comment]
>I had the same idea, that it could just be the reporting to apps mechanism and not the hardware. But how can I find out?

You can try outputting the raw NMEA (see https://github.com/barbeau/gpstest/blob/master/LOGGING.md for directions on how to do this with GPSTest) and see if the `GSA` string contains the PRNs of the Beidou or GLONASS sats.  See http://www.gpsinformation.org/dale/nmea.htm#GSA for more details.

>So do you think the LineageOS team is able to fix that issue?

I don't know for sure (it's been a while since I did a deep dive on custom ROMs) but my guess is no.  Qualcomm/Samsung would likely need to provide new drivers, which isn't going to happen.  LineageOS team would need to answer this question definitively.

**Comment by djdookie** [comment]
If I switch the option in GPS test to take the native API instead of the new Android 7.0 API, the result is the same. So I guess the underlying drivers/hardware are the reason. And if I watch the raw NMEA, I will get the same result?

**Comment by barbeau** [comment]
NMEA will likely show the same data now as it did for Android 6.0.  So I think this is your best shot to see if the Gnss chips etc is actually using the Beideu and GLONASS sets.

**Comment by djdookie** [comment]
Ok, but why does the option to use the native API not work?

**Comment by barbeau** [comment]
When a device is updated from Android 6.0 to Android 7.0, the entire Android platform implementation changes. This same platform feeds both the deprecated 6.0 APIs as well as the new 7.0 APIs, so it's likely that the same issues will be seen across both APIs.  My guess is that the simple passing of a NMEA string will survive the update for custom ROMs without problems. For more complicated APIs, though, the data structures may not match exactly, which might be why it's not showing used sats correctly for both sets of APIs.
